### ISSUE TITLE
Environment variable override / update

### ISSUE THREAD

**Issue by VladoPortos** [gitlabhq/terraform-provider-gitlab#1015]
### Feature Description

Would it be possible to add to "gitlab_project_variable" something like "force = true" and update it even when it is already existing... instead of failing and complaining that the variable is there already ? It should not be hard to implement since the API is supporting this action with simple:

```
"https://gitlab.com/api/v4/projects/{{ project}}/variables/SOM_VAR"
method: PUT
body: value="new_value
```

### Do you want to implement this?

- [ ] I would like to implement this myself 👷

**Comment by PatrickRice-KSC** [comment]
Hey @VladoPortos  - Thanks for the suggestion! What would be the benefit of doing something like this as opposed to importing the resource? It seems like you'd want to explicitly overwrite the variable (by importing it first) as opposed to just asserting that it should _always_ be destroyed.

**Comment by Cain175s** [comment]
https://gitlab.com/api/v4/projects/{{ project}}/variables/SOM_VAR"
method: PUT
body: value="new_value

**Comment by VladoPortos** [comment]
Hello @PatrickRice-KSC it's based on my experience I had recently... There were a couple of projects that had variables like PROD_SERVER_1, PROD_SERVER_2, and they have been already setup. My expectation would be for terraform not to fail when the variable is already there, just to update it and to fit the required state, stated in terraform....  To make it work I had to manually go and delete all the already existing variables and have to terraform recreated them... Maybe it's not the correct way of doing ?

**Comment by PatrickRice-KSC** [comment]
@VladoPortos  - That's actually pretty much exactly what you'd expect terraform to do in most cases 🙂 . Intuitively, if terraform attempts to create something that already exists (say, a new project), you wouldn't expect terraform to overwrite the existing project and destroy what already there. While there are obviously no APIs that allow overwriting projects, the principle for variables is essentially the same. If a resource is already present, you generally want terraform to fail to create it so that you need to either:

- destroy what's there because you don't care about it (like what you did), or
- import what's there so that terraform manages it moving forward.

They both achieve the same end-state, which is that terraform is managing the value of the resource moving forward.

In this particular case, you likely would have imported the variables using this syntax: `terraform import gitlab_project_variable.example '<project_id>:PROD_SERVER_1:*'`

hopefully that helps!

**Comment by VladoPortos** [comment]
@PatrickRice-KSC makes sense what you wrote, I completely missed the part about import of the variables. I think we can close this.

**Comment by PatrickRice-KSC** [comment]
Perfect, thanks @VladoPortos ~ Let us know if you have any more questions, we're always happy to help!
