### ISSUE TITLE
Topics API: extend by `title` property

### ISSUE THREAD

**Issue by wwwjon** [gitlabhq/terraform-provider-gitlab#1043]
### Feature Description

We extended the `topic` model in GitLab by a `title` property (see [docs](https://docs.gitlab.com/ee/api/topics.html)).

Could you please extend the Terraform Provider for GitLab to be able to manage the topic title as well?

### Do you want to implement this?

- [ ] I would like to implement this myself 👷

**Comment by Shocktrooper** [comment]
I looked at the Docs history page and saw that title only appeared on the 15.0-pre docs.  Is the title available now and the docs just never reflected it or is the title property coming in 15.0?

**Comment by nejch** [comment]
It is already deployed on gitlab.com (see https://gitlab.com/api/v4/topics), and will be available with self-managed 15.0.

I guess this would need https://github.com/xanzy/go-gitlab/pull/1458 released with go-gitlab first.

`title` would now be a required parameter in the API, but it didn't exist before. Would that need to be handled with `isGitLabVersionLessThan` or can it just be added?

**Comment by Shocktrooper** [comment]
In my opinion I would say that `isGitLabVersionLessThan` would probably be used because its not "optional" between the versions and is now a required field starting with 15.0 but I would defer to @timofurrer or @armsnyder for this.  We should also attach this ticket to the milestone ticket for 15.0 (which I think is the 4.x release of this provider)

**Comment by armsnyder** [comment]
We should add `title` as an optional attribute for now, and make it required in our next major release.

Using `isGitLabVersionLessThan` could be useful to communicate better error messages, but it is not strictly necessary. We could simply set the `title` request field if the attribute is not empty.

@Shocktrooper Has there been a 4.x discussion you could link to?

**Comment by nejch** [comment]
That sounds like a good compromise, especially since the topic feature hasn't been entirely usable before 15.0 anyway, so not sure if many people used it on their self-managed instance (this is an admin-only endpoint).

Though maybe 15.0 and 4.x is already ready by the time this is unblocked so `required` could happen from the start in that case I guess :grin:
