### ISSUE TITLE
Feature request: Support user GPG keys management

### ISSUE THREAD

**Issue by yan12125** [gitlabhq/terraform-provider-gitlab#1166]
### Feature Description

Hi, could you consider adding a new resource for managing GPG keys like [the one](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/user_gpg_key) from the GitHub provider? Apparently go-gitlab library already [supports that](https://github.com/xanzy/go-gitlab/pull/1330).

An example may be: (modified from examples for `github_user_gpg_key` and `gitlab_user_sshkey`)
```hcl
data "gitlab_user" "example" {
  username = "example-user"
}

resource "gitlab_user_gpgkey" "example" {
  user_id            = data.gitlab_user.example.id
  key                = "-----BEGIN PGP PUBLIC KEY BLOCK-----\n...\n-----END PGP PUBLIC KEY BLOCK-----"
}
```

When the field `key` is changed, there might be a forced replacement as current API [does not support updating an existing key](https://gitlab.com/gitlab-org/gitlab/-/issues/296977).

### Do you want to implement this?

- [x] I would like to implement this myself 👷 (may not be able to due to little experience with Go)

**Comment by yan12125** [comment]
I started looking into implementing it, and got a question. I'd like to manage GPG keys for the current user with a user token. Some people may want to manage GPG keys for whatever users with an admin token. The two scenarios need different APIs (ex: `POST /user/gpg_keys` and admin-only `POST /users/:id/gpg_keys`). How can I design the resource to fit both scenarios?

**Comment by timofurrer** [comment]
@yan12125 I suppose the simplest approach would be to just use the appropriate API depending on if the `user_id` attribute is given in the config. 

Let's consider the two examples:

```hcl
data "gitlab_user" "example" {
  username = "example-user"
}

resource "gitlab_user_gpgkey" "example" {
  user_id            = data.gitlab_user.example.id
  armored_public_key = "-----BEGIN PGP PUBLIC KEY BLOCK-----\n...\n-----END PGP PUBLIC KEY BLOCK-----"
}
```

This would use the `/users/:id/gpg_keys` API and require an admin token, because the `user_id` is given. AFAIK, even if the `:id` in the API call is the currently authenticated user - it is only available for admins!

The following example would use the `/user/gpg_keys` API and would operate on the currently authenticated users gpg keys determined by the token used:

```hcl
resource "gitlab_user_gpgkey" "example" {
  armored_public_key = "-----BEGIN PGP PUBLIC KEY BLOCK-----\n...\n-----END PGP PUBLIC KEY BLOCK-----"
}
```

This would apply for the create, read and delete calls (note that there isn't an update for this API). 

The schema for the `user_id` attribute would need to be `Optional: true` and all the fields would need to be `ForceNew: true`, because no update exist as you correctly stated).

We just need to document that properly and also include the behavior then changing from an admin to a non-admin token and vice-versa.

Does that help you to get started?

I'm looking forward to a PR 🎉  ... and let us know if you need anything else - may it be with the provider or Go ;) We are also active on [Discord](https://discord.gg/CCc6Pe5EYy)!

**Comment by yan12125** [comment]
Thank you very much for detailed suggestions! Now I have a rough idea for the code outline :)

> let the user know about this limitation and err

This sounds better to me. I've tried the admin-only API, and the error message does not mention it's admin-only. At first I thought there was something with my user token :joy: 

> let us know if you need anything else - may it be with the provider or Go ;) We are also active on [Discord](https://discord.gg/CCc6Pe5EYy)!

Great! Will pop up for further questions.

**Comment by yan12125** [comment]
Changed the field name `armored_public_key` => `key` as [the pull request template](https://github.com/gitlabhq/terraform-provider-gitlab/blob/main/.github/pull_request_template.md) suggests resource attributes to match 1:1 the names and structure of the API resource.
