### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by ThatGerber** [gitlabhq/terraform-provider-gitlab#133]
With what appears to be new maintainers, is there a roadmap for the project? I have a team that is relying on this for part of our workflow and are looking to contribute updates, but I'd like to know what's being worked on currently so that I don't encroach on others. 

Thanks!

**Comment by roidelapluie** [comment]
I do not think that there is work started except what is opened in pull requests for the moment.

**Comment by roidelapluie** [comment]
Feel free to discuss in issues what you will work on or create issues.

**Comment by ringods** [comment]
Roadmap update April 2020:

In Gitlab Enterprise Edition version 12, a server can be configured so groups and projects can be "soft-deleted" (#263). Since that moment, the acceptance tests became instable. I have been doing small updates focussing on getting the test suite stable again.

The `master` branch is now configured to run all test suites via Github Actions. In #291, I'm trying to get support for this "soft-delete" integrated in the Terraform provider. It is needed to get the test suites stable again. While this is not finished, no other pull requests will get integrated. I hope you all understand.

At the moment, this endeavour is mostly done by me within this provider codebase and @svanharmelen in the https://github.com/xanzy/go-gitlab codebase. If you, the reader of this update, have some spare time and you know your way around Go, TF provider testing and APIs, please help us debugging and getting to closure of this issue.

**Comment by ringods** [comment]
Rpadmap update May 2020:

The `soft-delete` functionality landed in [v2.5.1](https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/CHANGELOG.md#251-april-06-2020) of the provider. There have been a few increment releases after that.

Meanwhile, I'm going over the open Pull Requests one by one. I'm reaching out to the PR authors requesting a rebase if the PR is quite old. This backlog should reduce considerably in May and June timeframes.

**Comment by nicholasklick** [comment]
Thanks for everyones efforts! I am closing this for now.
