### ISSUE TITLE
[Feature Request] use full_path to define gitlab_project data source

### ISSUE THREAD

**Issue by mkjmdski** [gitlabhq/terraform-provider-gitlab#140]
Hi!

While refactoring my terraform repository I have found out that it would be awesome to provide same way to create gitlab_project data source as for gitlab_group by using full_path instead of id, this woulde make a code more human readable :).

**Comment by matejvelikonja** [comment]
This would be great, yes.

After a quick look, I think is a really simple fix. You would only need to change one line in the provider and it would work. `int` -> `string`.
This one: https://github.com/terraform-providers/terraform-provider-gitlab/blob/master/gitlab/data_source_gitlab_project.go#L17

`go-gitlab` lib already supports `interface` as and `id`, and gitlab `api` accepts either id or path.

Ref: 
- go-gitlab: https://github.com/xanzy/go-gitlab/blob/master/projects.go#L337
- gitlab api: https://docs.gitlab.com/ee/api/projects.html#get-single-project

But I think this is a breaking change, since we would change the Terraform type.

**Comment by mkjmdski** [comment]
Hi
Thanks for your reply. I think this could be implemented as a second constructor for data source what wouldn't break terraform type.

**Comment by armsnyder** [comment]
Other resources in this provider use the `project` attribute to mean either the project ID or project namespace+name (string).
