### ISSUE TITLE
Manual removal of a resource on provider will raise a "404 Not Found" error without any recover

### ISSUE THREAD

**Issue by marimp** [gitlabhq/terraform-provider-gitlab#209]
Hi there,

### Terraform Version
not related to the terraform version

### Affected Resource(s)
all resources

### Terraform Configuration Files
not related to Configuration File

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
A correct approach should be something like this (in this way the provider will be locally updated):

```go
	project, tag, err := projectAndTagFromID(d.Id())
	if err != nil {
		if strings.Contains(err.Error(), "404 Not Found") {
            d.SetId("")
            return nil
		}
		return err
	}
```

### Actual Behavior
there is a generic issue regarding the READ resource operation.
Considering as example the resource `resource_gitlab_tag_protection.go` (method `resourceGitlabTagProtectionRead`) code

```go
...
	project, tag, err := projectAndTagFromID(d.Id())
	if err != nil {
		return err
	}
...
```

In this way if the resource is not present on the server (404 Not Found response code), the provider return an error without deleting the local resource.
### Steps to Reproduce
N/A

### Important Factoids
N/A

### References
N/A

Is it possible to implement this approach in all resources?
Great Thanks for your attention
M.

**Comment by borisceranic** [comment]
Hi @ymatsiuk (and others),

Related to the issue described above, and to solution implemented in #223, I'd like to report that this issue exists also on `gitlab_group_membership` resources.

I'm adding my own notes here because this issue is still open, and also judging by the context, which consists of this issue, #222 and #223, this issue is very much still relevant, despite the fact that #223 resolved the problem for a few resource types.

## Steps to reproduce

1. Write Terraform project that manages group members of a group with ID **6xxxxx2**.
2. Configure Terraform to use GitLab API key using GitLab user account with Owner role in group **6xxxxx2**, but this user must be different from user ID **3xxxxx1** (we will later remove this user from the group so Terraform will be unable to manage said group ID **6xxxxx2**).
3. Import existing group members into Terraform state (a few members, including user ID **3xxxxx1** with username **username123131**). 
4. Apply Terraform project to gitlab, applying the diff, possibly adding/removing members as a result.
5. GitLab group memberships are now fully managed by Terraform.
6. Remove member with user ID **3xxxxx1** from the group ID **6xxxxx2** out of band using GitLab UI.
7. Run `terraform plan`.

## Expected result

```
  # gitlab_group_membership.main_owners["username123131"] will be created
  + resource "gitlab_group_membership" "main_owners" {
      + access_level = "owner"
      + group_id     = "6xxxxx2"
      + id           = (known after apply)
      + user_id      = 3xxxxx1
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

## Actual result

```
Refreshing Terraform state in-memory prior to plan...

[...snip...]
gitlab_group.main: Refreshing state... [id= 6xxxxx2]
data.gitlab_user.main_owners["username123131"]: Refreshing state...
[...snip...]
gitlab_group_membership.main_owners["username123131"]: Refreshing state... [id= 6xxxxx2: 3xxxxx1]
[...snip...]

Error: GET https://gitlab.com/api/v4/groups/6xxxxx2/members/3xxxxx1: 404 {message: 404 Not found}
```

## Workaround

1. Execute `terraform state rm KEY`.

    ```
    $ terraform state rm 'gitlab_group_membership.main_owners["username123131"]'
    Removed gitlab_group_membership.main_owners["username123131"]
    Successfully removed 1 resource instance(s).
    Releasing state lock. This may take a few moments...
    ```
2. Re-run `terraform plan`.

## Discussion

Now, since GitLab does not return anything but 404 in many scenarios, it's impossible to distinguish between legitimate 403 (where someone might have revoked Terraform's access to the group, in which case no corrective action is possible), and 404 as a legitimate message saying that "no such user X found in group Y", as [this comment rightly points out](https://github.com/terraform-providers/terraform-provider-gitlab/pull/222#issuecomment-558102211).

Given that GitLab is a bit annoying in this regard, and given that Terraform suggests providers should fall back gracefully (as [suggested by yourself here](https://github.com/terraform-providers/terraform-provider-gitlab/pull/222#issuecomment-558097495), Yurii), is it possible to fall back to the optimistic version of "resource not found, Terraform shall attempt to re-create it" behaviour?

If optimistic behaviour results in Apply failing hard because of some more serious issue, it's still better IMHO than not allowing Plan to proceed preemptively and having to manipulate state manually.

What do you think?

**Comment by ymatsiuk** [comment]
I'm totally agree and currently running custom built provider which does exactly this. My team insisted we use this strategy instead of manual `terraform state rm`. We also manage gitlab from centralized pipeline, which eliminates the lack-of-permissions-risk mentioned by @roidelapluie during our previous discussion.

**Comment by roidelapluie** [comment]
Hello , we are ok to reintroduce the previous behaviour (recreate when 404) for resources that can be imported.
