### ISSUE TITLE
Hello from GitLab. How can we help?

### ISSUE THREAD

**Issue by nicholasklick** [gitlabhq/terraform-provider-gitlab#376]
Hello @ringods @roidelapluie + all other maintainers and contributors 👋 

Speaking directly from GitLab, thank you for all your efforts to contribute to and steward this project, we greatly appreciate it.

I would like to introduce myself. I am an Engineering Manager at GitLab for the [Configure Team](https://about.gitlab.com/handbook/engineering/development/ops/configure/).

We are the team responsible for the new [GitLab Terraform integrations](https://docs.gitlab.com/ee/user/infrastructure/) as well as Kubernetes management and AutoDevops.

You can read more about [our product vision](https://about.gitlab.com/direction/configure/infrastructure_as_code/) for IaC.

In addition to all this product work, we have been asked directly by Hashicorp and by numerous customers to get more involved with this project. 

We would like to work collaboratively with you and all other maintainers and contributors to help further the vision of this project.

Here are a few items that have been brought our immediate attention:

- The need to expand support for EE features
- The need to migrate this project out of `/terraform-providers` and to `/gitlabhq` in order to support Hashicorp's new [Provider Registry](https://registry.terraform.io/browse/providers).

Looking forward to collaborating with all of you and continuing the conversation.

Cordially,

Nicholas

**Comment by roidelapluie** [comment]
Hello!

I am happy to see gitlab joining the effort.

I am OK to see the repo moved, but it is owned by Hashicorp and we do not have the right to move it ourselves. Will the provider still be reachable the same way for users? Is it possible to move it to gitlab instead of github? Did you consider it?

Currently Hashicorp also has the rights on this repo, so they decide who is maintainer etc (they trust our judgment, but they take the actions). You can take that, too, and manage the maintainers list.

I am interested of continuing to maintain this repo; and probably @ringods too. I guess that your team might bring a few maintainers too.

Regarding EE, you are totally right. There is a huge demand from gitlab customers to use this provider.

We already support some EE features, and Gitlab has provided us a license for the tests. We share that license between maintainers to be able to test against a local EE docker image, and it is integrated in CI. I'd like to be able to have a copy of the license too if I need to review or work on EE issues.

**Comment by ringods** [comment]
Hello @nicholasklick,

Very happy to see Gitlab stepping forward in the maintenance of this provider. I have only been a maintainer of this provider for a few months, mostly out of necessity to get some features in at a time when @roidelapluie had less time available to steward this provider.

Over the past months, I have been reviewing the backlog of open issues and pull requests and was able to get some of these integrated. Proof of that is the number of provider releases in the past months.

At the moment, I am unfortunately in the situation that I am bootstrapping a new company and lack the needed time to continue being a maintainer. I also want to reduce on the number of OpenSource projects I contribute too (count is at 23 ATM) due to changing personal interest. 

I have been (virtually) pushing a bit as well on Gitlab taking up the maintainer role for this provider:

https://gitlab.com/gitlab-org/gitlab/-/issues/232710

With the official transfer of this provider into the hands of Gitlab (the company), I choose to step down as an official maintainer. However, you can still expect a pull request if I would miss some functionality. ;-)

Closing note: you seem to have 2 organizations on Github:
- https://github.com/GitLab
- https://github.com/GitLabhq

**Comment by roidelapluie** [comment]
Thank you @ringods for the ride!!

**Comment by ringods** [comment]
While we are at it, the provider is not much without the (unofficial) Gitlab Golang SDK:

https://github.com/xanzy/go-gitlab

Looping in @svanharmelen in this discussion. @nicholasklick, you might check with him to see if he is open to give that SDK a home at Gitlab.

**Comment by svanharmelen** [comment]
Just FYI, I'm totally fine with "handing over" the `go-gitlab` package. I must admit that I'm not using the package myself anymore for years now, so all effort I put into it is only to help out the community 😏

**Comment by nicholasklick** [comment]
@svanharmelen thanks for the update. I will open an issue over on that project regarding it so it can be discussed with the community.

**Comment by nicholasklick** [comment]
@roidelapluie thanks for the update and I appreciate your stewardship.

> I am OK to see the repo moved, but it is owned by Hashicorp and we do not have the right to move it ourselves. Will the provider still be reachable the same way for users? Is it possible to move it to gitlab instead of github? Did you consider it?

The provider will be available via the Registry. I believe TF 0.13 is architected differently to point only to the registry, hence: https://github.com/terraform-providers/terraform-provider-gitlab/issues/383

We could move everything to GitLab immediately but the concern is replicating access, maintainerships, issues, existing PRs etc. I think the long term goal would obviously be to move it to GitLab.

**Comment by nicholasklick** [comment]
> We already support some EE features, and Gitlab has provided us a license for the tests. We share that license between maintainers to be able to test against a local EE docker image, and it is integrated in CI

If we need a new EE license one can be acquired.

**Comment by roidelapluie** [comment]
The current license:

```
Name         Julien Pivotto
Company      Julien Pivotto
Starts       2019-07-26
Expires      2020-07-25
User limit   30
```

**Comment by nicholasklick** [comment]
In terms of adding new maintainers, @armsnyder I see you are very active on this repo are you interested in being part of the maintainer team?

**Comment by armsnyder** [comment]
Hi @nicholasklick, it's nice to meet you! I would be happy to join the team and help however you see fit.

**Comment by nicholasklick** [comment]
@armsnyder great I will assign you some PRs to take a look at. Thanks so much for your efforts!

**Comment by armsnyder** [comment]
@nicholasklick Sounds good, I enjoy working on this project and will be around for the foreseeable future. It's great we're starting to clean up the backlog. I also tagged you in some old PRs which were approved and are merge-ready. 😉

**Comment by nicholasklick** [comment]
We have fully migrated this repo to GitLabs possession, enabled publishing to the Hashicorp registry, and shipped version 3.0.0.

Looking forward to much more progress in the near future.

**Comment by svanharmelen** [comment]
@nicholasklick back in September we briefly discussed the option to also transfer the [go-gitlab](https://github.com/xanzy/go-gitlab) package to GitLab. As mentioned before I'm not really using the package myself anymore for years now, so all effort I put into it is only to help out the community. But I must admit that it's becoming harder and harder to properly maintain the package without having a good sense of all the GitLab API changes myself.

Since this provider is completely build around the client I wrote, I would like to suggest to transfer the client to GitLab. It makes sure the client will be maintained by the people who fully understand the API it talks to and at the same time it gives you more control and flexibility to make future updates when needed for the provider.

Let me know you thoughts...

**Comment by nicholasklick** [comment]
@svanharmelen thank you for reaching out and thank you for all your efforts to support and maintain go-gitlab. It is very commendable. I will share this internally at GitLab and discuss what next steps should be. Stay tuned.

**Comment by svanharmelen** [comment]
Thanks! Staying tuned 😉

**Comment by svanharmelen** [comment]
Hi @nicholasklick 👋🏻 Any updates on this one?

**Comment by nicholasklick** [comment]
@svanharmelen I want to thank you for your continued service to the open source community.

I brought up a conversation internally about `go-gitlab` and the consensus is that GitLab generally doesnt take ownership of API clients. This one is interesting because the GitLab Terraform Provider is heavily dependent on `go-gitlab`.

There are some GitLab engineers that are interested in helping on an individual basis. I can help you try to find a new set of maintainers to steward the project if you need. For now though, our organization cannot take ownership of `go-gitlab` directly. I apologize of that is disappointing and I can try to help in whatever other way I can to support the project.
