### ISSUE TITLE
Migrating push_rules to v3.0.0

### ISSUE THREAD

**Issue by jacobkretz** [gitlabhq/terraform-provider-gitlab#460]
I've posted my question on the community [here](https://discuss.hashicorp.com/t/gitlab-provider-v3-migration/15364)

I'm trying to upgrade to the v3 of the provider and I have existing push_rules throughout ~100 repos.
Thanks in advance for any help.

### Terraform Version
0.12.29

### Affected Resource(s)
gitlab_project_push_rules (old vs new)

### Terraform Configuration Files
Simple successfully deployed gitlab_project v2 config and then migrating the push_rule resource to the v3 project location, and removing the legacy resource.

### Expected Behavior
Not sure, but I need some type of migration path.  I'm looking for guidance.  My assumption that when upgrading to v3 it doesn't auto migrate the old state to the new state. If I need to remove the state manually or mv it I'm willing to try but if there was an easier path I'd like some confirmation.

### Actual Behavior
terraform plan errors out with the following error after upgrade to v3: Error: no schema available for module.ui_email_template_project.gitlab_project_push_rules.default[0] while reading state; this is a bug in Terraform and should be reported

### Steps to Reproduce
terraform plan

### Important Factoids
The existing projects have count statement in them so the resources are structured in state as (example): module.ui_email_template_project.gitlab_project_push_rules.default[0]

**Comment by armsnyder** [comment]
Hi @jacobkretz. v3 of this provider was a major release, and there is no supported migration path for the now-removed `gitlab_project_push_rules ` resource. I would suggest bulk-removing all `gitlab_project_push_rules` resources from your module state, using something like `terraform state list | grep gitlab_project_push_rules | terraform state rm` (not tested). Assuming you have `gitlab_project` resources in your module, you will probably see a new `push_rules` block appear in the diff of each `gitlab_project`, which is where push rules are configured now. You may have been following some of the many issues around push rules; we determined that the resource needed to be folded into `gitlab_project` because of how GitLab automatically creates push rules when a project is created. If you believe there should be a migration path, and if you're able to migrate your ~100 repos, we'd certainly appreciate if you'd reply with your migration steps and we can add some migration documentation to the provider for this.

**Comment by armsnyder** [comment]
Hey I'm closing this issue for the above reason since I didn't hear back.
