### ISSUE TITLE
Resource gitlab_project gets 400 error many times when creating projects

### ISSUE THREAD

**Issue by sdwerwed** [gitlabhq/terraform-provider-gitlab#470]
Hi there,

When creating projects using terraform and gitlab provider I get `400 Bad Request {message: {limit_reached: []}, {name: [has already been taken]}, {path: [has already been taken]}}` this is happening because sometimes the POST /api/v4/projects for creating projects is getting `Internal Server Error 500`, it is creating the project correctly just the response is lost, so the terraform sends the request again to create the project and gets error Bad Request 400 already exists.

### Terraform Version
Terraform v0.13.4
+ provider registry.terraform.io/gitlabhq/gitlab v3.0.0

### Affected Resource(s)
- gitlab_project 

### Debug Output
Read the description and terraform logs on [gist](https://gist.github.com/sdwerwed/cbcf9bc5dcb996f96f3986a48aaad8ef )

### Expected Behavior
It should create always the projects without 500 or 400 error code

### Actual Behavior
Sometimes POST /api/v4/projects gets 500

### Steps to Reproduce
1) Use this version of this code https://github.com/sdwerwed/terraform-gitlab-provider-example/tree/count-issue-500
2) Use the GitLab CE latest docker image (version 13.5.1)
3) `terraform apply` or `terraform apply` `terraform destroy` `terraform apply`

**Comment by qwerty1979bg** [comment]
@sdwerwed
Since the "500 Internal Server Error" is coming from the GitLab server and not the Terraform provider, you might want to file a bug report on its tracker: https://gitlab.com/gitlab-org/gitlab/-/issues

You may experiment with lowering Terraform's parallelism to 1:
https://www.terraform.io/docs/commands/apply.html#parallelism-n

Additionally, make sure that the GitLab server has enough resources available (CPU/RAM/IOPS).

As for the Terraform provider itself, it would be good if it handled the "500 Internal Server Error" in a more graceful way.

**Comment by armsnyder** [comment]
As I understand the issue, the provider is returning a 500 error during resource creation, and then on subsequent apply it is returning a 400, because the resource was actually created upstream.

In this case unfortunately there's isn't really anything the provider can do, since Terraform does not have any mechanism of auto-importing resources created upstream, as far as I am aware. You will have to run `terraform import` commands yourself to resolve the issue.

As @qwerty1979bg pointed out it may be an issue with the upstream GitLab API or your server configuration if it is a common problem.

Please let us know if you have a suggestion for how the provider can handle this error more gracefully.

**Comment by sdwerwed** [comment]
I did some tests on my GitLab server that is running as a docker container in windows 10. 

It fails with parallelism greater than 1:
`terraform apply -auto-approve -parallelism=2` it fails because of `POST http://localhost:8080/api/v4/projects: 400 {message: {limit_reached: []}, {name: [has already been taken]}, {path: [has already been taken]}}`

It works with parallelism equal to 1:
`terraform apply -auto-approve -parallelism=1`

**Comment by armsnyder** [comment]
@sdwerwed Can you add your TF config to the gist please?

**Comment by sdwerwed** [comment]
@armsnyder The module is on the git, you can check the git URL in the issue I created in section steps to reproduce, is this enough for you?

**Comment by armsnyder** [comment]
@sdwerwed I see it now, thanks.

**Comment by armsnyder** [comment]
I see from `didnotwork.log` that there were several `500 Internal Server Error` errors returned from GitLab, and I also see that there was no `201 Created` response for the project `projectgreen1`.

Compare that to `worked.log`, where there were zero `500 Internal Server Error` errors, and there was a `201 Created` response for the project `projectgreen1`.

The GitLab client we use will retry requests when it gets a `500 Internal Server Error` response.

One possibility is we could add some arguments to the provider configuration allowing you to set a custom rate limit, or disable internal retries. Would either of those options work for you? As mentioned before we can't add logic to the provider to auto-import upstream resources that already exist, as it would violate Terraform design principles.

**Comment by sdwerwed** [comment]
For me `terraform apply -auto-approve -parallelism=1` is enough, I just wanted to report this bug to help the community. 
So you think that the server is not able to handle high requests/s? If I understood correctly then adjusting the rate might solve the issue.  About disabling retries maybe is not a good approach as with error 500 we don't know if the project is created or not.

**Comment by armsnyder** [comment]
> So you think that the server is not able to handle high requests/s?

That's my suspicion, yes.

Assuming the issue is overloading GitLab, one idea would be to add a provider argument `gitlab_api_parallelism` to control the parallelism of the client specifically. Perhaps it could only affect POST/PUT/PATCH requests. It's basically the same as setting `-parallelism=1` as you mentioned, though, so without knowing more I think there's not enough value to go after this right now.

We can keep this issue open for a while to gauge the impact and gather suggestions from the community. 😄 If you can look into your server logs and find what's causing the 500 that could also help.

**Comment by sdwerwed** [comment]
@armsnyder I created parallel async requests to create 9 projects with python using GitLab API and there is the same issue as in terraform with parallelism >1, the server gets random 500 Internal Server Error but the projects are created.

**Comment by sdwerwed** [comment]
@armsnyder we found the issue https://gitlab.com/gitlab-org/gitlab/-/issues/288013 and current_user.project_authorizations.safe_find_or_create_by!(project: @project, access_level: group_access_level)

**Comment by armsnyder** [comment]
@sdwerwed Awesome, thanks for following through with that. It sounds like this is a GitLab internal issue which is being addressed and not something we need to react to in this plugin then.
