### ISSUE TITLE
Moving subgroup deletes underlying projects

### ISSUE THREAD

**Issue by toddmichael** [gitlabhq/terraform-provider-gitlab#574]
### Terraform Version
```
Terraform v0.14.6
+ provider registry.terraform.io/gitlabhq/gitlab v3.4.0
```

### Affected Resource(s)
- gitlab_group
- gitlab_project

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "gitlab_group" "ansible_roles" {
  name                    = "ansible-roles"
  path                    = "ansible-roles"
  description             = "Ansible roles"
  parent_id               = gitlab_group.ace.id        # <---- this is what I updated
  subgroup_creation_level = "owner"
  project_creation_level  = "maintainer"
  request_access_enabled  = true
}

resource "gitlab_project" "ansible_roles" {
  for_each = local.ansible_roles

  name                                             = each.key
  description                                      = each.value
  default_branch                                   = "master"
  namespace_id                                     = gitlab_group.ansible_roles.id
  visibility_level                                 = "internal"
  initialize_with_readme                           = true
  approvals_before_merge                           = 0
  only_allow_merge_if_pipeline_succeeds            = false
  only_allow_merge_if_all_discussions_are_resolved = false
  remove_source_branch_after_merge                 = true
  container_registry_enabled                       = false
  issues_enabled                                   = true
  merge_requests_enabled                           = true
  packages_enabled                                 = true
  pipelines_enabled                                = true
  shared_runners_enabled                           = false
  snippets_enabled                                 = true
  wiki_enabled                                     = false

  lifecycle {
    # guard against accidental destruction of this repository
    prevent_destroy = true
  }
}
```

### Plan output

```
Terraform will perform the following actions:

  # gitlab_group.ansible_roles must be replaced
-/+ resource "gitlab_group" "ansible_roles" {
      ~ full_name                         = "old_path / ansible-roles" -> (known after apply)
      ~ full_path                         = "old_path/ansible-roles" -> (known after apply)
      ~ id                                = "3589" -> (known after apply)
        name                              = "ansible-roles"
      ~ parent_id                         = 2147 -> 6994 # forces replacement
      ~ runners_token                     = (sensitive value)
      ~ visibility_level                  = "internal" -> (known after apply)
      ~ web_url                           = "https://..{redacted}...ansible-roles" -> (known after apply)
        # (12 unchanged attributes hidden)
    }

  # gitlab_project.ansible_roles["base"] will be updated in-place
  ~ resource "gitlab_project" "ansible_roles" {
        id                                               = "4088"
        name                                             = "base"
      ~ namespace_id                                     = 3589 -> (known after apply)
        tags                                             = []
        # (29 unchanged attributes hidden)
    }
.... 
# repeat for other ansible role projects
```

### Expected Behavior

- Subgroup would relocated its new parent group
- Projects would follow

or at the very least there would be an error indicating that Terraform couldn't destroy my projects given `prevent=destroy`.

### Actual Behavior

- Subgroup was destroyed and recreated under new parent group (normal)
- All projects appear to have been deleted

### Apply Output

```
gitlab_group.ansible_roles: Destroying... [id=3589]
gitlab_group.ansible_roles: Still destroying... [id=3589, 10s elapsed]
gitlab_group.ansible_roles: Still destroying... [id=3589, 20s elapsed]
gitlab_group.ansible_roles: Destruction complete after 26s
gitlab_group.ansible_roles: Creating...
gitlab_group.ansible_roles: Creation complete after 1s [id=7048]
gitlab_project.ansible_roles["base"]: Modifying... [id=4088]
gitlab_project.ansible_roles["vault"]: Modifying... [id=4359]
....
# repeat for remaining ansible role projects

Error: PUT https://..{redacted}../api/v4/projects/4359/transfer: 404 {message: 404 Project Not Found}

  on projects.tf line 126, in resource "gitlab_project" "ansible_roles":
 126: resource "gitlab_project" "ansible_roles" {

Error: PUT https://..{redacted}../api/v4/projects/4088/transfer: 404 {message: 404 Project Not Found}

  on projects.tf line 126, in resource "gitlab_project" "ansible_roles":
 126: resource "gitlab_project" "ansible_roles" {

...
# repeat for remaining ansible role projects
```

### Steps to Reproduce

- Change subgroup parent id
- `terraform apply`

### Important Factoids

Pretty severe given:

1. moving a group (destroy/recreate) deletes all projects despite no indication from plan that this is what will happen
2. destructive action bypasses lifecycle destruction prevention

**Comment by Shocktrooper** [comment]
I do not work on this project yet as I do not know GO but was curious as to what the behavior should be or what is possible and here are my findings.

GitLab's API which is used by terraform to do all of its management appears to not have the capability to do a group transfer like you can via the UI
References
- UI Transfer: https://docs.gitlab.com/ee/user/group/#transfer-a-group
- API Reference on Updating a Group: https://docs.gitlab.com/ce/api/groups.html#update-group

After further looking this also appears to be an open ticket from 2 years ago for GitLab to add this capability to the API instead of only via the UI
References
- GitLab feature request ticket: https://gitlab.com/gitlab-org/gitlab/-/issues/23831

With all of this information I have a few recommendations
1.  Ask GitLab to prioritize the ticket so that it can be implemented here cleanly after upgrading the dependent go-gitlab [project](https://github.com/xanzy/go-gitlab)
2. Update the documentation to note that if you change the parent ID then this will wipe out all of the projects underneath that group [Doc Link](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/group#parent_id)

**Comment by Shocktrooper** [comment]
In order to work around this you might have to do something similar to the following
- https://www.terraform.io/docs/cli/import/index.html
- https://learn.hashicorp.com/tutorials/terraform/state-import?in=terraform/state&utm_source=WEBSITE&utm_medium=WEB_IO&utm_offer=ARTICLE_PAGE&utm_content=DOCS

1. Manually move all of the groups via the UI to where you want them to be [Doc](https://docs.gitlab.com/ee/user/group/#transfer-a-group)
2. Create the placeholder for the group resource and its projects inside of terraform if not already there for the GitLab group
3. Do an import on the group & all of its projects [Group Import Reference](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/group#importing-groups) & [Project Import Reference](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/group#importing-groups)
4. Remove the old references inside of terraform
5. Do a terraform plan to see if everything is imported correctly
NOTE: This is untested and only the basic flow of how this group move should work.  GitLab/terraform might behave differently in reality.  If you do test this out please update this ticket with how the flow should really work and any caveats you run into so that others can reference this in the future till GitLab implements this functionality in their API

**Comment by adamantike** [comment]
According to https://about.gitlab.com/releases/2021/12/22/gitlab-14-6-released/#use-the-api-to-transfer-a-group-to-a-parent-group, it seems it should be possible now to fix this underlying issue, and only move the group without affecting GitLab projects?

**Comment by armsnyder** [comment]
Yep, this should be possible with special handling of the `parent_id` attribute in the `resourceGitlabGroupUpdate` function to call the new /transfer API.
