### ISSUE TITLE
[Feature Request] Add "Labels to be notified" for gitlab_service_slack resource

### ISSUE THREAD

**Issue by toddmichael** [gitlabhq/terraform-provider-gitlab#765]
### Feature Request

Please consider adding **Labels to be notified** option to `gitlab_service_slack` resource.

### References

- GH-233

**Comment by nowyp** [comment]
Deployments channel configuration and Alerts also missing

**Comment by PatrickRice-KSC** [comment]
@timofurrer  - I was looking at grabbing this issue, but I'm not seeing the ability to set this [through GitLab's Slack Service API](https://docs.gitlab.com/ee/api/integrations.html#createedit-slack-integration) right now. This seems to be mirrored within the go-gitlab API library:  https://github.com/xanzy/go-gitlab/blob/master/services.go#L1265

am I missing something that it's set to an api alignment tag?

**Comment by timofurrer** [comment]
@PatrickRice-KSC good catch. I've actually recently looked into this and created:

* https://github.com/gitlabhq/terraform-provider-gitlab/issues/790

However, for the missing attributes we are currently blocked by the referenced go-gitlab issue.

I'm closing the issue here in favor of #790 where we can keep track of the upstream API alignment. 🎉
