### ISSUE TITLE
[Feature request] Add support for Gitlab boards

### ISSUE THREAD

**Issue by KoenR3** [gitlabhq/terraform-provider-gitlab#772]
We set up our boards in the same manner over many projects.  It would help a lot to have access to board list and board resources of the boards API https://docs.gitlab.com/ee/api/boards.html through Terraform

**Comment by Shocktrooper** [comment]
I think there might need to be a slight update to go-gitlab in order to utilize this resource to its full effectiveness if at all. As there seems to have been some updates to the API that are not reflected in go-gitlab. 
https://github.com/xanzy/go-gitlab/blob/master/boards.go
https://docs.gitlab.com/ee/api/boards.html

**Comment by Shocktrooper** [comment]
Not sure what I was seeing before but I did another check and it seems it should be good to go and the go-gitlab work is all there

**Comment by KoenR3** [comment]
Are there any plans to add this?  We are currently struggling with setting up the same swimlanes for every project.  We use the REST API but are using Terraform for all the rest so it would integrate much better to do everything through Terraform.
