### ISSUE TITLE
gitlab_project: Support creating project for specific user

### ISSUE THREAD

**Issue by eddiemcbride** [gitlabhq/terraform-provider-gitlab#85]
### Terraform Version
Terraform v0.11.7
+ provider.gitlab v1.1.0

### Affected Resource(s)
Please list the resources as a list, for example:
- gitlab_project
- gitlab_user

### Terraform Configuration Files
```
# Define variables
variable "gitlab_token" {}
variable "gitlab_url" {}
variable "gitlab_username" {}
variable "gitlab_usertitle" {}
variable "gitlab_userp" {}
variable "gitlab_useremail" {}
variable "gitlab_projectname" {}
variable "gitlab_projectdesc" {}

# Set provider
provider "gitlab" {
    token = "${var.gitlab_token}"
    base_url = "${var.gitlab_url}"
}

# Add a user
resource "gitlab_user" "new_gitlab_user" {
  name             = "${var.gitlab_usertitle}"
  username         = "${var.gitlab_username}"
  password         = "${var.gitlab_userp}"
  email            = "${var.gitlab_useremail}"
  is_admin         = false
  can_create_group = true
  is_external      = false
}

# Create a project under the new user
resource "gitlab_project" "new_gitlab_project" {
  name        = "${var.gitlab_projectname}"
  description = "${var.gitlab_projectdesc}"
  visibility_level = "private"
  namespace_id = "${gitlab_user.new_gitlab_user.id}"
}
```

### Expected Behavior
It should create the new GitLab project under the new user namespace.

### Actual Behavior
It creates the project under a random user's namespace

### Comments
This is my first time posting an issue here so if I've done this incorrectly, I apologize.  We have had multiple people try this internally and we can easily recreate the scenario.   Also, we are using GitLab Enterprise Edition 11.7.4-ee.

**Comment by armsnyder** [comment]
I was able to reproduce this. Based on my reading of the [create-project API](https://docs.gitlab.com/ee/api/projects.html#create-project) and [create-project-for-user API](https://docs.gitlab.com/ee/api/projects.html#create-project-for-user), the `namespace_id` argument is meant to be used to specify a group id, not a user id.

My proposal is we add a `user_id` argument to the `gitlab_project` resource, and if it is set, then use the create-project-for-user API to create the project.

**Comment by tyriis** [comment]
As this is still an issue (at least for me), I have had a closer look.
related to: https://docs.gitlab.com/ee/api/namespaces.html namesaces, user_ids and group ids are not the same.
After a little bit of debugging i found out that it is possible to create a project for a user. But it is not possible to get the namespace id from the terraform provider.

Not totaly sure about how to implement the fetch of the namespace but would be good to have it as part of the user and group objects. For some reason groups have always same id then namesapces (groups dont start with id 1, they use the next available namesapce id as id). This is the reason why this work for groups.

An adaption to the implementation could resolve the namespace for the user and group and reference it as `namespace_id` attribute, so things would be much more clearer.

**Comment by PatrickRice-KSC** [comment]
I was looking through older ticket a bit, and this one seems a bit tricky. As tyriis noted, this would still be an issue. I will note that the the *actual* result isn't that the project is created within a random user's namespace, it would create it within the namespace of based on the token passed into the terraform provider, but that's only really important if someone is finding this issue later and trying to troubleshoot 😄 

So the main issue here is that this will be blocked by GitLab's API not returning the namespace_id of the user, but given that the desire here is to create a new user then create a project within that user's namespace, I think we could probably implement a `gitlab_namespace` data source based on the [list namespaces](https://docs.gitlab.com/ee/api/namespaces.html#list-namespaces) API. The namespace for the user is almost always their username when they're first created, so a sample terraform for this would be:

```
provider "gitlab" {
    token = var.gitlab_token
    base_url = var.gitlab_url
}

# Add a user
resource "gitlab_user" "new_gitlab_user" {
  name             = var.gitlab_usertitle
  username         = var.gitlab_username
  password         = var.gitlab_userp
  email            = var.gitlab_useremail
  is_admin         = false
  can_create_group = true
  is_external      = false
}

# Retrieve the user's namespace after creation
data "gitlab_namespace" "user_namespace" {
  search = gitlab_user.new_gitlab_user.username
  depends_on = [gitlab_user.new_gitlab_user]
}

# Create a project under the new user
resource "gitlab_project" "new_gitlab_project" {
  name        = var.gitlab_projectname
  description = var.gitlab_projectdesc
  visibility_level = "private"
  namespace_id = gitlab_user.new_gitlab_user.id
}
```
Not quite ideal because the link from user -> namespace is a little bit fragile, but seems like the best we can do with the current APIs. There is a namespace membership API, but it only works for admins (so it's likely not feasible here).

If we think this is a reasonable solution though, I can get a namespace data source added pretty easily I think.

**Comment by timofurrer** [comment]
@PatrickRice-KSC thanks for the investigation! I agree that while this may work it'll be a little fragile, because `data.gitlab_namespace` may yield more than one result - even worse when there may be multiple results it may not be sorted and returned in a different order every time.

> There is a namespace membership API, [..]

Which API are you referring to?

> [..] but it only works for admins (so it's likely not feasible here).

Thinking about this, who is able to create a project in another users namespace? I would assume that this is only the user owning that namespace and administrators. Given terraform is authenticated with a non-admin token it can use `gitlab_project` without giving a `namespace_id` to create it in the user namespace. Otherwise, terraform authenticates with an admin token and that admin-only API could be used.
Point being, I think it might be feasible :)

**Comment by PatrickRice-KSC** [comment]
@timofurrer  - This is the API I was referring to: https://docs.gitlab.com/ee/api/users.html#user-memberships-admin-only

I agree with your comment about the namespace looking being fragile too. My thought last night while I was looking at it was that since the user was newly created, it would only _have_ one namespace, but that assumption breaks upon second run when the user being created by TF may have been added to other groups.

> Thinking about this, who is able to create a project in another users namespace?
Uh, good point. I'm actually not sure about the answer to this question. I'll have to test this out a bit to see if an admin can create a project within a user's namespace. Even if we can assume that the token passed into TF is an admin token though, we will have the issue that the user-membership API would return a potential list (even if on first run that list would only have 1 result, assuming you filter on namespace with the API) and there isn't a good way to filter out the user's namespace without making the assumption that their username is the namespace value.

**Comment by timofurrer** [comment]
> My thought last night while I was looking at it was that since the user was newly created, it would only have one namespace, but that assumption breaks upon second run when the user being created by TF may have been added to other groups.

It even could break on the first run, right? The reason for this is that `search=timo` would search for `timo`, `timothy`, `timon`, .. or can one use some form of regex?

> I'll have to test this out a bit to see if an admin can create a project within a user's namespace.

Well, if an admin can't then I suppose no one can and therefore this entire request would be invalid, because it would imply that a user can only create a project for themselves, meaning that `gitlab_project` with providing a namespace works, right?

By now, all I can think of is fragile (even though it would work in theory). I'll quickly check later if I can propose an upstream implementation to respond the `namespace_id` for a `GET /users/:id` request.

**Comment by PatrickRice-KSC** [comment]
> It even could break on the first run, right?

I actually tested that, and I didn't seem to getting "begins-with" search result, so my guess is that we can pass in wildcards, but the documentation isn't entirely clear on that point. It may depend on how generic the username is as well.

> By now, all I can think of is fragile (even though it would work in theory).

Yeah, I'm in the same place as you. I think this should probably be blocked based on upstream API until we can get a namespace_id from the user because otherwise it's just too fragile; before we do that I'll run a quick test tonight on whether or not an admin can even create a project within a user's namespace. If that doesn't work, this whole approach is moot.

**Comment by timofurrer** [comment]
> before we do that I'll run a quick test tonight on whether or not an admin can even create a project within a user's namespace.

It works, I just verified :)

I'm on an implementation in GitLab to expose the `namespace_id`. Let's see how that goes. In the meantime, I'll block it here :)

**Comment by PatrickRice-KSC** [comment]
Do you happen to have that issue ID handy in GitLab? I can drop a notification tag on it so that I can follow it there too.

**Comment by timofurrer** [comment]
Yes, I've just submitted my MR here: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/82045
