### ISSUE TITLE
GitLab Release support

### ISSUE THREAD

**Issue by timofurrer** [gitlabhq/terraform-provider-gitlab#984]
We've had some discussions around this already, but I want to get one started here and get your opinions on it.

Currently the provider is tested against the latest GitLab release for CE and EE (that's not what is on gitlab.com). Thus, today that's 14.9 released 22nd March 2022.

We could define that "officially" a specific provider release "supports" the versions it's tested against. For the upcoming provider release 3.13.0 that would be GitLab 14.9.

However, that doesn't mean that the provider doesn't work for a GitLab 14.8 or even an older release. It most likely will, thus the provider actually "supports" it.

As a rule of thumb I can also say that if we introduce support for a non-backwards compatible feature, e.g. a new field in an API which would be rejected by an older version, we try to check for the GitLab version first, before adding the field to the actual request (e.g. see https://github.com/gitlabhq/terraform-provider-gitlab/pull/867).

The goal of this issue is to:

1. document our strategy for what version of GitLab a specific provider release "officially" supports.
2. maybe:
   a.  add some automated recurring tests, testing the latest release against the last X GitLab releases
   b. define followup 

My initial gut feeling also is that we shouldn't make a too big of a deal out of it - there haven't been much issue regarding this in the past. I have the feeling that people who don't update their GitLab instances, also don't update their provider - because these are the same people or colleagues within a company or at least have the influence to also trigger GitLab instance upgrades.

I think we can almost keep what we are doing, but document it so we have a place for reference, e.g. in the CONTRIBUTING.md and in the CHANGELOG.md ...

WDYT?

**Comment by jtymes** [comment]
I agree that it's likely not a big deal. Documenting _somewhere_ that the provider aims to be compatible with the latest release could be enough.

To be more clear for consumers, a doc convention could be used when new fields are added, like you did with #867. If done consistently, they could be removed automatically later on with `make doc-clean 14.10` and it could remove any that were <14.8 or something. This would be docs-only, so no validation in the code.

**Comment by Stromweld** [comment]
In chef docs they started adding to new resources or new options of a resource the version of chef-client it was introduced in so users on older versions wouldn’t be confused why it didn’t work. You could do the same for provider here and have version of gitlab resources or additional attributes are supported in. With the notion it’s supported up to the latest version.

**Comment by Shocktrooper** [comment]
Would there be some value in adding a test that checks the GitLab version for some resources/attributes. Basically a different version of the ee check. Also documentation as well would help

**Comment by timofurrer** [comment]
> Would there be some value in adding a test that checks the GitLab version for some resources/attributes. Basically a different version of the ee check.

We've been using this pattern so far to address skipping test steps:

https://github.com/gitlabhq/terraform-provider-gitlab/blob/d18aee439f62646265b5dd0b954f500449cc85a8/internal/provider/resource_gitlab_managed_license_test.go#L72

>  Also documentation as well would help

This is mainly the way to go I think for new things (attributes, values, behavior, resources, datasources, ...).

**Comment by Shocktrooper** [comment]
Yup so that is for the acceptance tests but I was thinking about almost that same exact pattern say for the create function of a resource that would error out a plan/apply if someone tried to use attributes or the resource itself on an unsupported version of GitLab. 

That kind of scenario should result in some sort of HTTP error I imagine anyways on apply so we mind as well tell the end user why in a prettier and better formatted way this isn't going to work.

**Comment by armsnyder** [comment]
A good first step would be to include in the release notes the version of GitLab that we tested against. At least this way people can choose their provider version based on their current GitLab version. We already have a CI workflow step that generates release notes -- we just need to append the GitLab version.

As a later followup we could add an additional EE/CE test that runs against the latest GitLab version from X months ago, whatever we decide our support window to be. Since as you said this hasn't been an issue yet, we could start with 6 months. This gives us a min and max supported GitLab version that we can add to the release notes.

In general I'd discourage hand-writing code branches to cover different GitLab versions. This feels like a recipe for tech debt, as we'd need to continually clean up branches for out-of-support versions. But there are always exceptions.

**Comment by Shocktrooper** [comment]
@armsnyder I don't see code branches specifically mentioned in here what about only the past 3 months support wise to match GitLab proper?

**Comment by timofurrer** [comment]
FYI: The PR #1095 to support GitLab 15.0 implements a test matrix in the workflows to test against the last three GitLab releases.

This will be documented in the ChangeLog ...
